version: '3.7'
services:
  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    build:
      context: ./images/influxdb/
      dockerfile: ./${TYPE}/Dockerfile
      args:
        INFLUXDB_TAG: ${INFLUXDB_TAG}
    image: "influxdb"
    networks:
      - influxdb-network-2
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
#      - ./influxdb/config/:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      #- "8082:8082"
      # UDP Port
      #- "8089:8089/udp"

#  telegraf:
#    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
#    build:
#      context: ./images/telegraf/
#      dockerfile: ./${TYPE}/Dockerfile
#      args:
#        TELEGRAF_TAG: ${TELEGRAF_TAG}
#    image: "telegraf"
#    # Telegraf requires network access to InfluxDB
#    networks:
#      - influxdb-network
#    environment:
#      HOSTNAME: "telegraf-getting-started"
#    volumes:
#      # Mount for telegraf configuration
#      - ./telegraf/:/etc/telegraf/
#      # Mount for Docker API access
#      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - influxdb

  kapacitor:
  # Full tag list: https://hub.docker.com/r/library/kapacitor/tags/
    build:
      context: ./kapacitor/
      dockerfile: ./Dockerfile
      args:
        KAPACITOR_TAG: ${KAPACITOR_TAG}
    image: "kapacitor"
    # Kapacitor requires network access to Influxdb
    networks:
      - influxdb-network-2
    environment:
      MODEL_PATH: "/var/lib/kapacitor/model/adsmodel.pkl"
      KAPACITOR_URL: "http://kapacitor:9092"      
    volumes:
      # Mount for kapacitor data directory
      - ./kapacitor/data:/var/lib/kapacitor/data
      - ./kapacitor/UDFs:/var/lib/kapacitor/UDFs
      - ./kapacitor/TICKscripts:/var/lib/kapacitor/TICKscripts
      - ./kapacitor/kapacitor.log:/var/log/kapacitor/kapacitor.log
      # Mount for kapacitor configuration
      - ./kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - ./kapacitor/tmp/:/tmp/
      # Mount Anomaly Detection Model
      - ./model:/var/lib/kapacitor/model
    ports:
      # The API for Kapacitor is served on port 9092
      - "9092:9092"
    depends_on:
      - influxdb      

  chronograf:
    # Full tag list: https://hub.docker.com/r/library/chronograf/tags/
    build:
      context: ./images/chronograf
      dockerfile: ./${TYPE}/Dockerfile
      args:
        CHRONOGRAF_TAG: ${CHRONOGRAF_TAG}
    image: "chrono_config"
    # Chronograf requires network access to Influxdb
    networks:
      - influxdb-network-2    
    environment:
      RESOURCES_PATH: "/usr/share/chronograf/resources"
    volumes:
      # Mount for chronograf database
      - ./chronograf/data:/var/lib/chronograf
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - kapacitor
      - influxdb
#      - telegraf

  grafana:
    # Full tag list: https://hub.docker.com/r/grafana/grafana/tags
    image: "grafana/grafana:latest"
    networks:
      - influxdb-network-2    
    volumes:
      # Mount for grafana database and pluging folder
      - ./grafana/data:/var/lib/grafana
#      - grafana-storage:/var/lib/grafana
      # !!! Be careful!!! Mount for grafana configuration. !!! Be careful, file must exest on host before run a container!!!
 #      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
     # Mount for grafana provisioning mechanism
      - ./grafana/provisioning:/etc/grafana/provisioning
#    user: "104"
    ports:
      # The WebUI for Grafana is served on port 3000
      - "3001:3000"
    depends_on:
      - kapacitor
      - influxdb    
      
#  documentation:
#    build:
#      context: ./documentation
#   ports:
#      - "3010:3000"

volumes:
  grafana-storage:

networks:
  influxdb-network-2:
    name: influxdb-network-2