apiVersion: 1

datasources:
  - name: InfluxDB - db - printer
    type: influxdb
    access: proxy
    database: printer
    user: grafana
#   lvl=warn msg="[Deprecated] the use of password field is deprecated. Please use secureJsonData.password" logger=provisioning.datasources datasource name="InfluxDB - db - printer"
#    password: grafana
    url: http://influxdb:8086/
    jsonData:
      httpMode: GET
    secureJsonData:
      password: grafana